language: php

php:
#  - '5.2'
#  - '5.3'
#  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer install

script:
  - mkdir -p .build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/phpcs ./ --standard=./phpcs.config.xml -s

# We should also add codecov.
#after_success:
#- bash <(curl -s https://codecov.io/bash)